// src/components/TwinStudy/WorkflowSteps.vue
<template>
  <div v-if="workflow && workflow.nodes" class="workflow-steps">
    <div class="workflow-container">
      <div 
        v-for="(node, index) in workflow.nodes"
        :key="node.id"
        class="workflow-item"
      >
        <div class="workflow-node-wrapper">
          <div 
            :class="['workflow-node', {
              'active': node.id === currentNodeId,
              'done': isNodeDone(node.id, index)
            }]"
          >
            <img 
              v-if="getIconUrl(node)"
              :src="getIconUrl(node)"
              :alt="node.data?.config?.title"
              :class="['workflow-icon', {
                'inverted': node.id === currentNodeId || isNodeDone(node.id, index)
              }]"
            />
            <div v-else class="workflow-dot"></div>
          </div>
          <span 
            :class="['workflow-label', {
              'active': node.id === currentNodeId
            }]"
          >
            {{ node.data?.config?.title }}
          </span>
          <div 
            v-if="index < workflow.nodes.length - 1"
            :class="['workflow-connector', {
              'done': isNodeDone(node.id, index)
            }]"
          ></div>
          <div class="workflow-tooltip">
            {{ node.data?.config?.desc || node.data?.config?.title }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const BASE_IMG_URL = 'https://bailian.cdut.edu.cn'

const props = defineProps({
  workflow: {
    type: Object,
    required: true
  },
  currentNodeId: {
    type: String,
    default: ''
  }
})

const getIconUrl = (node) => {
  const icon = node.data?.config?.icon
  if (!icon) return null
  if (icon.startsWith('/')) {
    return `${BASE_IMG_URL}${icon}`
  }
  return icon
}

const isNodeDone = (nodeId, index) => {
  if (!props.currentNodeId) return false
  const currentIndex = props.workflow.nodes.findIndex(n => n.id === props.currentNodeId)
  return currentIndex > index
}
</script>

<style scoped>
.workflow-steps {
  width: 100%;
  margin: 16px 0;
  padding: 16px;
  background: #f8fafd;
  border-radius: 16px;
  border: 1px solid #edf2f7;
  overflow-x: auto;
}

.workflow-container {
  display: flex;
  align-items: center;
  gap: 0;
  min-width: max-content;
}

.workflow-item {
  display: flex;
  align-items: center;
}

.workflow-node-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  position: relative;
  max-width: 120px;
}

.workflow-node {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s;
  border: 2px solid;
  z-index: 10;
}

.workflow-node.active {
  background: #2563eb;
  border-color: #2563eb;
  box-shadow: 0 4px 12px rgba(37, 99, 235, 0.4);
  transform: scale(1.1);
}

.workflow-node.done {
  background: #10b981;
  border-color: #10b981;
}

.workflow-node:not(.active):not(.done) {
  background: white;
  border-color: #e5e7eb;
  opacity: 0.6;
}

.workflow-icon {
  width: 20px;
  height: 20px;
  object-fit: contain;
}

.workflow-icon.inverted {
  filter: brightness(0) invert(1);
}

.workflow-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #9ca3af;
}

.workflow-node.active .workflow-dot,
.workflow-node.done .workflow-dot {
  background: white;
}

.workflow-label {
  margin-top: 8px;
  font-size: 11px;
  font-weight: 500;
  text-align: center;
  color: #6b7280;
  width: 100%;
  padding: 0 4px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.workflow-label.active {
  color: #2563eb;
}

.workflow-connector {
  height: 2px;
  width: 32px;
  margin-top: -20px;
  transition: background-color 0.5s;
  background: #e5e7eb;
}

.workflow-connector.done {
  background: #10b981;
}

.workflow-tooltip {
  position: absolute;
  top: -48px;
  left: 50%;
  transform: translateX(-50%);
  background: #1f1f1f;
  color: white;
  font-size: 10px;
  padding: 4px 8px;
  border-radius: 4px;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.2s;
  white-space: nowrap;
  z-index: 20;
}

.workflow-node-wrapper:hover .workflow-tooltip {
  opacity: 1;
}
</style>

// gemini-clone-assistant/components/WorkflowSteps.tsx

import React from 'react';
import { WorkflowData } from '../types';

interface WorkflowStepsProps {
  workflow: WorkflowData;
  currentNodeId?: string;
}

const BASE_IMG_URL = 'https://bailian.cdut.edu.cn';

const WorkflowSteps: React.FC<WorkflowStepsProps> = ({ workflow, currentNodeId }) => {
  if (!workflow || !workflow.nodes) return null;

  // We sort nodes based on edges to create a logical sequence if possible, 
  // or just use the order provided.
  const nodes = workflow.nodes;

  return (
    <div className="w-full my-4 p-4 bg-[#f8fafd] rounded-2xl border border-[#edf2f7] overflow-x-auto">
      <div className="flex items-center gap-2 min-w-max">
        {nodes.map((node, index) => {
          const isActive = node.id === currentNodeId;
          const isDone = nodes.findIndex(n => n.id === currentNodeId) > index;
          const iconUrl = node.data?.config?.icon?.startsWith('/') 
            ? `${BASE_IMG_URL}${node.data.config.icon}` 
            : node.data?.config?.icon;

          return (
            <React.Fragment key={node.id}>
              <div className="flex flex-col items-center group relative max-w-[120px]">
                <div 
                  className={`w-10 h-10 rounded-full flex items-center justify-center transition-all duration-300 border-2 z-10 ${
                    isActive 
                      ? 'bg-blue-600 border-blue-600 shadow-lg scale-110' 
                      : isDone 
                        ? 'bg-green-500 border-green-500' 
                        : 'bg-white border-gray-200 opacity-60'
                  }`}
                >
                  {iconUrl ? (
                    <img 
                      src={iconUrl} 
                      alt={node.data?.config?.title} 
                      className={`w-5 h-5 object-contain ${isActive || isDone ? 'brightness-0 invert' : ''}`} 
                    />
                  ) : (
                    <div className={`w-2 h-2 rounded-full ${isActive || isDone ? 'bg-white' : 'bg-gray-300'}`} />
                  )}
                </div>
                
                <span className={`mt-2 text-[11px] font-medium text-center truncate w-full px-1 ${isActive ? 'text-blue-600' : 'text-gray-500'}`}>
                  {node.data?.config?.title}
                </span>

                {/* Tooltip */}
                <div className="absolute -top-12 left-1/2 -translate-x-1/2 bg-[#1f1f1f] text-white text-[10px] py-1 px-2 rounded opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap z-20">
                  {node.data?.config?.desc || node.data?.config?.title}
                </div>
              </div>

              {index < nodes.length - 1 && (
                <div className={`h-0.5 w-8 -mt-6 transition-colors duration-500 ${isDone ? 'bg-green-500' : 'bg-gray-200'}`} />
              )}
            </React.Fragment>
          );
        })}
      </div>
    </div>
  );
};

export default WorkflowSteps;
